apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vnaxqa3or-nodejs 
  janus-idp.io/tekton: vnaxqa3or-nodejs
  backstage.io/kubernetes-id: vnaxqa3or-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vnaxqa3or-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml